---
title: "STAT 440 Statistical Data Management - Fall 2021"
output: html_document
---

## Homework00 (Not a Real Assignment)
### Due: Monday Nevruary 1, 2021 11:59 pm US Central Time
#### Created by Prof. Christopher Kinson

Grading Rubric (per question):  
2 points if complete and correct  
1 point if incomplete or incorrect  
0 points if no attempt made  


**Retrieving your work**

This and all future homework .md files are written in Markdown. The .md file is rendered as an .html file for easier viewing. This and all future homework assignments are located in the **homework** directory within the **stat440-sp21-course-content** repo, i.e. **stat440-sp21-course-content/homework** in GitHub. It is always recommended that you **pull** (or refresh) the **stat440-sp21-course-content** repo to ensure that you have the most updated version of all course content including the homework assignments. After pulling (or refreshing) the **stat440-sp21-course-content** repo, the homework file will be in the homework directory. Once you have accessed the .md file, copy all text from the .md file and paste all text into your reproducible document file (either .Rmd or .ipynb file). 

**Submitting your work**

In your individual student repo (named as your netID), you are to submit ***two*** files:

a. Your reproducible document file (either .Rmd or .ipynb file) which should be saved as homework#-netID.Rmd or homework#-netID.ipynb depending on your preferred software. For example, my homework 01 file would be saved as homework01-kinson2.Rmd.

b. Your rendered reproducible document file (.html) which should be saved as homework#-netID.html. For example, my homework 01 file would be saved as homework01-kinson2.html.

**Do not place your files in a sub-directory (or folder).** You have an unlimited number of submissions, but only the latest proper submission (commit and push) will be viewed and graded. You are allowed to only use one software language per homework file. This means that you cannot mix software languages (R and Python) in one single homework file. **Remember the .Rmd (or .ipynb) file needs to render properly to .html before submitting.** 


***

Undergraduates are expected to complete the problems **#1-#8**. Graduate students are expected to complete all problems.

**The following problems should be completed by you as an individual. If any problem asks you a particular question, be sure to answer it completely (with code, written sentences, or both). Written sentences should not appear in code chunks or code cells. Written sentences should appear in Markdown syntax unless specifically stated otherwise.**

***Do not change anything in this file above the double line. Doing so will prevent your homework from being graded.***

***
***

### Use only one programming language for this entire homework assignment. Use the URLs to access the data. No local files allowed.


**#1** (Markdown) Using Markdown syntax, make a numbered list with your first name in normal text as the first item and your last name in bold text as the second item.

1. Yulin
2. **Song**

**#2** (Syllabus, Markdown, Course announcements) Who are the course staff? Write your answer as an unordered list with each course staff member's name in italic text.

* *Chris*
* *Jim*
* *Jaideep*

**#3** (Personal interest survey) What are your expectations of the course staff for this course? What grade do you plan on earning in this course and why?

I would expect the course to help me to be better at storing data, cleaning data, structuring data etc. I would be expecting to get A or A- because I would be working hard not only for the grade, but for the work ethic and the skills and knowledges needed for my grad school and professional career.
